apiVersion: v1
kind: Pod
metadata:
  name: nginx-deklarativ
  labels:
    app: webserver
    environment: learning
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
