# Übung 5.6: Secrets verwenden
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: app
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - echo "Username: $DB_USER";
        echo "Password: $DB_PASS";
        echo "Files in /secrets:";
        ls -la /secrets;
        sleep 3600

    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: username
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: password

    volumeMounts:
    - name: secret-volume
      mountPath: /secrets
      readOnly: true

  volumes:
  - name: secret-volume
    secret:
      secretName: api-keys
