# Übung 5.5: Secrets
# HINWEIS: In Produktion niemals Secrets in Git committen!
apiVersion: v1
kind: Secret
metadata:
  name: api-keys
type: Opaque
stringData:
  api_key: "sk-1234567890abcdef"
  api_secret: "geheimer-api-schluessel"
